name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Arduino CLI
        uses: arduino/setup-arduino-cli@v1
        with:
          version: 0.33.1
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install ESP8266 Board Core
        run: |
          arduino-cli core update-index
          arduino-cli core install esp8266:esp8266

      - name: Install Libraries
        run: |
          arduino-cli lib install "Blynk"
          arduino-cli lib install "NewPing"
          arduino-cli lib install "Servo"

      - name: Build Arduino Sketch
        run: |
          arduino-cli compile --fqbn esp8266:esp8266:nodemcuv2 aquabot
